### ISSUE TITLE
@ symbol in content causes error

### ISSUE THREAD

**Issue by gblouin** [brianwigfield/Meek#1]
I ran into an issue while playing with Partial content.  I found that I had added content text that included a single @ symbol.  "Imagine Schools @ Indigo Ranch"

This was causing errors in the project because Razor is apparently trying parse the content.

**Comment by brianwigfield** [comment]
You are right using the @ symbol like that (not in an email address) needs to be escaped for the razor view engine using @@.
This can be added into the framework to automatically escape these easy cases.

The content actually gets sent through the processing like a normal MVC view which allows you to execute code inside of your content, I haven't tested it but you can probably even nest partial content this way.

**Comment by gblouin** [comment]
My concern is that non-technical users will enter it and be surprised when the whole page breaks.  The only way I could fix was to go into my database and update or delete the content entry.

Love this project btw, such a wonderful way to bolt on a straight-forward CMS when you don't need a lot of extra rigor!

**Comment by brianwigfield** [comment]
Yes I agree it should be fixed.
FYI you could also edit it in the browser if you know what the edit url is, or go to /Meek/List to get a list of all the defined content to edit.

**Comment by brianwigfield** [comment]
Resolved in latest source and in nuget package v0.75

**Comment by gblouin** [comment]
Thanks Brian!  Updating now.
